apiVersion: v1
appVersion: 1.7.12
deprecated: true
description: DEPRECATED Open-source web application written in Go and React.js that
  provides the tools to visualize your monitoring data and easily create alerting
  and automation rules.
engine: gotpl
home: https://www.influxdata.com/time-series-platform/chronograf/
keywords:
- chronograf
- visualizaion
- timeseries
name: chronograf
version: 1.1.1
