apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-bifrost
spec:
  replicas: {{ .Values.bifrostReplicas }} 
  template:
    metadata:
      labels:
        app: esp-bifrost
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - esp-bifrost
              topologyKey: "kubernetes.io/hostname"
      containers:
      # [START esp]
      - name: esp
        image: {{ .Values.espImage}}
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service={{ .Values.bifrostHostValue}}",
          "--rollout_strategy=managed",
          "-z",
          " "
        ]
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "150m"
      # [END esp]
        ports:
        - containerPort: 8081
      - name: bifrost
        image: {{ .Values.bifrostImage}}
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: https://{{ .Values.bifrostHostValue}}
        - name: REQUIRE_HTTPS
          value: "True"
        - name: PORT
          value: "8080" 
        - name: APP_WORKERS 
          value: "1"
        - name: APP_HOST 
          value: "0.0.0.0"
        - name: COSMO_HOST
          value: "http://cosmo"
        - name: LOG_OUTPUT 
          value: "json" 
        - name: LOG_LEVEL 
          value: "DEBUG" 
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"
