apiVersion: v1
kind: Service
metadata:
  name: internal-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: cosmo
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - {{ .Values.loadBalancerSourceRanges}}
  selector:
    app: cosmo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP